name: Automerge

on:
  push:
    branches:
      - main
      - master
      - 'ethereum:master'

  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.AARON_GITHUB_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          required-labels: ":arrow_heading_down: pull"
          dry-run: false
