name: Automerge

on:
  # Try enabling auto-merge for all open pull requests. (Only recommended for testing.)
  push:
    branches:
      - main
      - master
      - 'ethereum:master'

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.AARON_GITHUB_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          required-labels: ":arrow_heading_down: pull"
          dry-run: false
